### ISSUE TITLE
Should TODO be split into issues?

### ISSUE THREAD

**Issue by spuder** [UltimateHackingKeyboard/electronics#1]
There is a list of remaining todos

https://github.com/UltimateHackingKeyboard/electronics/blob/master/TODO

Thoughts on opening a github issue for each? 
- can assign tasks to people
- prevent duplicate work from two people working on same problem at same time
- encourage task specific discussions

I'm willing to do the tedious work of migrating the todo's to issues if you want to go down that route.

**Comment by mondalaci** [comment]
@spuder Thank you for your offer, I'd happily take it!
