### ISSUE TITLE
Re-wrap and reposition the "Unscrew the 5 large below the keycaps..."

### ISSUE THREAD

**Issue by spuder** [UltimateHackingKeyboard/electronics#10]
Re-wrap and reposition the "Unscrew the 5 large below the keycaps and the 1 screw on the PCB" text to be more readable. 

<img width="486" alt="screen shot 2015-12-09 at 8 38 50 pm" src="https://cloud.githubusercontent.com/assets/242382/11706513/96cb5408-9eb6-11e5-8505-bf2e6686bac8.png">

**Comment by spuder** [comment]
@mondalaci Could I get some feedback on what you are looking for here? 

Here is one proposal that rephrases for less characters and moves text a little further away from the vias / holes. 

<img width="575" alt="screen shot 2015-12-09 at 9 56 46 pm" src="https://cloud.githubusercontent.com/assets/242382/11707293/c94d88de-9ebf-11e5-95fa-b180a98e6dff.png">
<img width="456" alt="screen shot 2015-12-09 at 9 56 53 pm" src="https://cloud.githubusercontent.com/assets/242382/11707294/cb4355ce-9ebf-11e5-87a8-1ee6b4c071db.png">
<img width="633" alt="screen shot 2015-12-09 at 10 01 10 pm" src="https://cloud.githubusercontent.com/assets/242382/11707324/61981b04-9ec0-11e5-8dce-695bf6c9af34.png">

**Comment by mondalaci** [comment]
@spuder Your suggested solution looks great! I'd love to merge a pull request implementing the above.
