### ISSUE TITLE
Add fixating pins to the Cherry MX module

### ISSUE THREAD

**Issue by spuder** [UltimateHackingKeyboard/electronics#13]
Add fixating pins to the Cherry MX module so that PCB mounted switches can be used, too

![](http://www.wasdkeyboards.com/media/guide/plate_pcb.jpg)

There are two libraries that already have this

https://github.com/geekhack-org/kicad-library

https://github.com/c0z3n/cherrymx-eagle

The latter would need to be converted to kicad. (done)
- [x] Ensure license is compatible with the UHK https://github.com/geekhack-org/kicad-library/issues/1
- [x] Get cherry mx library https://github.com/UltimateHackingKeyboard/ugl-kicad-libs/pull/2

**Comment by mondalaci** [comment]
Done.
