### ISSUE TITLE
Add pins for Matias switches if possible

### ISSUE THREAD

**Issue by spuder** [UltimateHackingKeyboard/electronics#14]
Not impossible, but difficult
![2l9c](https://cloud.githubusercontent.com/assets/242382/11707438/bbf6f5a6-9ec1-11e5-8d0d-43a99596a363.png)

**Comment by mondalaci** [comment]
I've seen two examples of implementing this. I assume that the double hole version probably works better, but maybe we should ask Matias.

![beforeassembly](https://cloud.githubusercontent.com/assets/300402/11764827/a714018a-a13f-11e5-9346-3016ce0d1573.jpg)
![ctkkkjg](https://cloud.githubusercontent.com/assets/300402/11764828/a71b38b0-a13f-11e5-84e5-d5adee3a7c29.jpg)

**Comment by spuder** [comment]
I've contacted Matias support a couple of times asking if they have cad files ~~with no response~~, the VP of engineering will get back to me. I haven't been able to find any github projects that contains a matias libraries, though this one looks promising. 

https://github.com/kiibohd/pcb/tree/master/ICED%20-%20Right/prettylib

**Comment by spuder** [comment]
Matias switch cad files can be downloaded from here:

http://matias.ca/switches/Matias_Switch_3D.zip

They are in the format .EPRT .IGS and .STEP They will need to be converted to a .kicad_mod file

Here are the blueprints: 

Quiet Click
http://matias.ca/switches/quiet/blueprints/?p=4

Click
http://matias.ca/switches/click/blueprints/?p=1

Quiet Linear
http://matias.ca/switches/linear/blueprints/?p=1

**Comment by mondalaci** [comment]
Great job! Looks like all of the above information is indirectly accessible via http://matias.ca/switches/

Just emailed Matias and asked them about the suggested universal switch footprint along with some further info.

**Comment by spuder** [comment]
I spent some time creating a custom part from the blueprints, only to later find that the buttons library included in kicad already includes a matias part! 

The only consideration is that it uses relatively large pads. On the cherry MX, the holes are 1.5 mm inner diameter and 2.5 mm outer diameter. 

The matias library has 1.5mm inner diameter and 3mm outer diameter. Not a problem, just needs a little extra clearance.
<img width="898" alt="screen shot 2016-01-06 at 5 46 18 pm" src="https://cloud.githubusercontent.com/assets/242382/12159217/9f779470-b49d-11e5-96ce-5426c4039605.png">

All 3 of their switches use the same layout. 

<img width="357" alt="screen shot 2016-01-06 at 5 43 41 pm" src="https://cloud.githubusercontent.com/assets/242382/12159127/0d6314b0-b49d-11e5-9827-5e3462e3a388.png">
<img width="800" alt="screen shot 2016-01-06 at 5 42 34 pm" src="https://cloud.githubusercontent.com/assets/242382/12159132/10a624dc-b49d-11e5-9f95-eaa134cde492.png">
<img width="924" alt="screen shot 2016-01-06 at 5 44 07 pm" src="https://cloud.githubusercontent.com/assets/242382/12159141/1ca639e8-b49d-11e5-9aec-cbe6a139445d.png">

The other consideration is that the pins numbers are swtiched between the cherry mx and matias libraries (pin 1 is on left in matias, right side on cherry)

**Comment by spuder** [comment]
This has been completed for the left hand side.
https://github.com/spuder/electronics/tree/feature/%2313_matias
 It has the following considerations that need to be reviewed
- 4 new vias near iso switches are different from the via part that is in the ugl library. I don't see a way to change the built in via into a ugl:via 

<img width="875" alt="screenshot 2016-01-11 17 56 34" src="https://cloud.githubusercontent.com/assets/242382/12251517/dcf5a2fe-b88c-11e5-9c2f-6cd6851049a9.png">
- Switch 27 has a hole that goes off the end of the board. Will that cause a problem? 

<img width="599" alt="screenshot 2016-01-11 17 59 20" src="https://cloud.githubusercontent.com/assets/242382/12251551/0bb17e88-b88d-11e5-9ff1-e8512cf8f2c5.png">

The following are items that shouldn't cause problems, but should be closely inspected
- verify that there is enough space for the vertical capacitor

<img width="217" alt="screenshot 2016-01-11 18 01 33" src="https://cloud.githubusercontent.com/assets/242382/12251618/8d111e3e-b88d-11e5-967e-558eb20545e4.png">
- verify the new layout of capacitors has enough room

<img width="175" alt="screenshot 2016-01-11 18 01 39" src="https://cloud.githubusercontent.com/assets/242382/12251649/c07ac608-b88d-11e5-9ff0-12c64cbee160.png">

Lastly, because of the new switch layout that includes the stabilizing holes for the cherry mx boards, there is a DRC that fails. There is no way around this. We could: 
1. Allow the DRC to fail for the overlapping pads
2. Create a new custom part that includes strangely shaped holes

Neither solution is ideal. There has been some discussion in the kicad forms on how to handle this situation. 

https://forum.kicad.info/t/multiple-pin-components/2006

<img width="793" alt="screenshot 2016-01-11 18 05 31" src="https://cloud.githubusercontent.com/assets/242382/12251683/1301db64-b88e-11e5-8252-a8e203edb953.png">
<img width="673" alt="screenshot 2016-01-11 18 05 46" src="https://cloud.githubusercontent.com/assets/242382/12251684/1442c90c-b88e-11e5-8d1a-9341e9c1ab96.png">

**Comment by spuder** [comment]
I spoke with matias. They don't offer any sample kits, but they will sell me 3 keys (one of each type) for $10. Otherwise we would need to buy a 200 key set for $50 (plus another $50 for the keycaps). 

http://matias.ca/order/#switches

**Comment by mondalaci** [comment]
Sorry for the late reply, these have been busy days.

The most important thing is that the Cherry switches should probably be reversed for optimized backlighting. The reason is that unlike most keyboards the UHK makes heavy use of the front side of the keycaps for featuring the labels of the Mod layer. Because of this, the front labels should be lit. This needs the LEDs to be featured on the user-facing sides of the switches, not the other way.

![81pg25laqtl _sl1500_](https://cloud.githubusercontent.com/assets/300402/12311376/05d2f872-ba57-11e5-99c0-455cb6233fc2.jpg)

Above is the KBT Pure 60% keyboard to illustrate my point.

In light (no pun intended) of the above, what route would you take, Spencer? I'd rather vote for reversing the switches which would negate some or all of your work. I'd hate to do that but I think it'd make sense to future-proof the design in this respect.

Please let me answer your other questions too a little bit later.

**Comment by spuder** [comment]
I agree reversing the part would be best. Doing so would be a very big change and I don't know how soon the board is to being finalized and delivered. I won't be sad if we don't use the work I've done so far because it has been a learning experience. I've used eagle, but never kicad. 

Two approaches

## Iterative

Keep working on the board in phases. Ship the version that is ready at the final date. 

6.0 => matias + cherry mx stabilizer
7.0 => reversed switches
8.0 => led lights (with reversed switches). 

## Incremental

Overhaul board to have all the desired features

reversed switches + matias + cherry mx stabilizer + led lights

---

It all comes down to timing. I estimate the latter would require changing over 30% of the board layout, and would take several months plus new prototypes. If you think there is time, I'm willing to help either way.

**Comment by spuder** [comment]
@mondalaci I've been thinking about this more.  

I'm ok to throw away the work that I've done on the matias switches, though I think it still might be useful because while adding the cherry mx stabilizer holes, I've moved traces and components out of the way. Rotating the part 180 degrees will reuse those holes. 

Here is what I think is the best course of action

To the master branch:
- Add the new pogo plugs 
- Swap the atmega for the teensy
- Add the 4P4C

Then try and merge my matias branch. If the merge works, we just need to rotate the components. If the merge doesn't work, then I'm ok to start over. I'm much faster at kicad now. 

I suspect this would take a few weeks. Once that is done:

If sufficient time, add the led circuitry
If approaching deadline, skip the leds and get a prototype made. 

Thoughts?

**Comment by spuder** [comment]
There is a major obstacle to rotating the keycaps around

<img width="582" alt="screenshot 2016-01-14 20 04 56" src="https://cloud.githubusercontent.com/assets/242382/12344444/51fcb186-bafa-11e5-8cdf-054e392e5dc2.png">

switch 13 might need to be rotated 90 degrees, or left upside down not sure if that would make the led lighting look weird.

**Comment by mondalaci** [comment]
This one shouldn't be a problem. Just talked to Andras and he said that the FFC connector can be moved a little farther away from SW13. Relative to SW13 the new position of the FFC connector should be x-4.364mm and y-11.257mm.

**Comment by mondalaci** [comment]
Thanks for elaborating on the two approaches, good thinking! I'd rather prefer your incremental approach (reversed switches + matias + cherry mx stabilizer + led lights).

But before executing this complex change it'd be worth to wait for Andras to overhaul the soft keepout areas and slighly tweak the shape of the PCB based on the updated CAD data. He should be ready on the upcoming week, and after that this sweeping change could take place.

At this point I'm only unsure about how to implement LED backlighting for Matias switches. Unlike for Cherry switches this is rather nontrivial but the above overhaul shouldn't be affected by adding Matias LEDs later on.

**Comment by mondalaci** [comment]
Regarding the overlapping stabilizer pins of the Cherry switches I think the best solution is to create two additional hybrid footprints that are the same as the hybrid footprint except without left / right stabilizer pins. We could use one of these modified footprints wherever necessary.

**Comment by mondalaci** [comment]
Thanks for looking into Matias keycaps, Spencer! I'm not terribly worried about them right now. I'm rather concerned about future-proofing the PCB to make it compatible with Matias switches. We should be able to scavenge most (if not all) of the Matias keycaps from existing Matias/ALPS keyboards that can be purchased from eBay for example.

**Comment by spuder** [comment]
For reference, the ergodox infinity was recently updated to support all major keycaps

https://www.massdrop.com/buy/infinity-ergodox?utm_source=Sailthru&mode=guest_open&utm_medium=email&referer=SQPK6L&utm_term=Community%20-%20Style%20-%20MAU%20(Active
- Cherry
- Matias
- Gateron
- Zealios

![](https://massdrop-s3.imgix.net/product-images/MD-6758_20150330194040_3fb82ae6812febe4.jpg?auto=format&fit=crop&w=761&dpr=1)

It also has usb3 support

**Comment by mondalaci** [comment]
Good find!

I can't see how Gateron differs from Cherry. I think Gateron simply has a single version featuring fixation pins. Is Zealios different from the Cherry? I don't think so. It's nice that Matias is supported but elongated holes might be problematic for soldering purposes.

**Comment by mondalaci** [comment]
Please let me answer the rest of your questions, Spencer.

It shouldn't be a problem that switch 27 has a hole that goes off the end of the board. Worst case scenario: the stabilizer pin in question will be cut off. But Andras will try to make space for the stabilizer pin in the case.

The vias in question can't be changed to ugl:via because these vias aren't separate modules. You can simply choose the desired via from the via combobox that is located rightwards of the track width combobox below the top menu and then right-click on the via, select it from the pop-up menu, then click on the Change Via Size and Drill menu item.

I think there should be enough space for the vertical capacitor.

When you said "verify the new layout of capacitors has enough room" did you mean resistors? I assume you meant the R22 and its close friends. We'll end up using a resistor network instead of the individual resistors so as long as the DRC is ok the current layout it should be fine.

**Comment by spuder** [comment]
For reference, it looks like the corsair k70 uses upside down cherry mx leds. The keycaps also have the transparent letters near the top

![](http://i.imgur.com/z8O7KXG.jpg)
![](http://i.imgur.com/8vSMkRg.jpg)

**Comment by mondalaci** [comment]
Almost every keyboard on the market uses upside LEDs. Downside LEDs only make sense when the letters are not only top-printed but side-printed, too.

**Comment by spuder** [comment]
@mondalaci I see you added a git submodule for the kibohd footprints. 

I've looked into using their footprint instead of the one I made. 

https://github.com/kiibohd/pcb/issues/3

Thoughts on using their footprint? 

Pros:
- Tested

Cons: 
- Matias switch holes are slightly different from matias blueprints
- Can PCB manufacture drill oblong shaped holes? 
- Is CERN license compatible with UHK license? 
- PCB will 'look' kind of like the ergodox with the oblong holes

If you don't have a problem with these, then I suggest we just use their footprint instead of the one I made.

**Comment by mondalaci** [comment]
@spuder I'd prefer to use your version mainly because it should be easier to solder due to the circular drill holes. I've only added the kiibohd repo because it may be worth to use their Kinetis processor module.

I didn't think that license incompatibility may be an isssue. The way I though about it is that these are two separate projects. Would it be problematic to use a CERN-licensed component in a GPL-licensed project?

**Comment by mondalaci** [comment]
Done.
