### ISSUE TITLE
Cherry MX LED lights

### ISSUE THREAD

**Issue by spuder** [UltimateHackingKeyboard/electronics#15]
Allow modders to use cherry mx switches with LEDs
- [x] Update library to use cherry mx pinout with led holes. [example](http://cherrycorp.com/wp-content/uploads/2014/12/11.gif)   done: https://github.com/UltimateHackingKeyboard/ugl-kicad-libs/pull/2
- [ ] Choose a led driver that handles PWM
- [ ] Determine if sufficient pins available on the AtMega for led driver
- [ ] Design charlieplexing matrix

Optional features
- [ ] Software defined brightness, [like code keyboard https://codekeyboards.com/]) 
- [ ] Individually toggle buttons (caps lock, num lock)

Related https://github.com/UltimateHackingKeyboard/electronics/issues/13

**Comment by mondalaci** [comment]
It'd be useful to take a look at some open source keyboard designs that have backlighting. I'd rather go for a simple implementation that supports a single PWM channel for all the LEDs. So I mean no per-LED backlighting.

**Comment by spuder** [comment]
Some possible led drivers

[74HC595 Shift Register](https://www.adafruit.com/products/450) 
- only needs 3 pins (SPI)
- can daisy chain
- Have to do charlie plexing in software

[MAX7219 Led Driver](https://www.adafruit.com/products/453)
- Handles control and refreshing. Greatly simplifies code
- Kind of expensive.

I'm leaning towards the first option because it is cheaper. 

The teensy has an spi library https://www.pjrc.com/teensy/td_libs_SPI.html

**Comment by mondalaci** [comment]
I'm aware of these options. Unfortunately, the 74HC595 only allows for a single LED per pin and the MAX7219 is fabulously expensive.

I've been suggested the TPS61193 lately which may work for us. We could string about a dozen of LEDs per OUTx pin.

![tps61193](https://cloud.githubusercontent.com/assets/300402/12406236/83cf1c22-be4b-11e5-960b-688832ccd75a.png)

I personally don't feel confident in my abilities to choose the best part for this purpose and will surely talk to an electronics engineer before making a choice. But suggestions are always welcome!

**Comment by spuder** [comment]
Looking at the [ergodox infinity](https://github.com/kiibohd/pcb/tree/master/ICED%20-%20Left), they are using the  [IS31FL3731C](http://www.mouser.com/ProductDetail/ISSI/IS31FL3731C-SALS2/?qs=rnuWwpjhhVvfjmOe6D9bPQ%3D%3D)

**Comment by mondalaci** [comment]
Yes, I know, but [nobody has it on stock](https://octopart.com/search?q=IS31FL3731C) which is not very promising.

**Comment by mondalaci** [comment]
Apparently, this IC is [available](https://octopart.com/search?q=IS31FL3731) without the closing C in its part name.

**Comment by mondalaci** [comment]
Done. We went with the IS31FL3731-SALS2.
