### ISSUE TITLE
Where do you get the libraries from?

### ISSUE THREAD

**Issue by spuder** [UltimateHackingKeyboard/electronics#22]
I know you are really busy, so I'll try and be as self sufficient as possible. 

I'm updating the readme with instructions so others can easily contribute. There are 3 libraries required
- special
- opendous
- uhk libs

I've figured out how to install opendous and the uhk libs, but even after a couple hours of searching, I can't find the 'special' library

<img width="550" alt="screen shot 2015-12-12 at 7 48 11 pm" src="https://cloud.githubusercontent.com/assets/242382/11765178/9d3f08b6-a109-11e5-8759-68d78272605b.png">

Do you know where that library is located? Once I find it I'll document it so others can find it.

**Comment by mondalaci** [comment]
- The "uhk libs" library can be found at https://github.com/UltimateHackingKeyboard/ugl-kicad-libs
- I think this is the relevant Opendous library but please let me know if it doesn't work: https://code.google.com/p/opendous/downloads/detail?name=KiCad_Libraries-2012-10-18.zip&can=2&q=
- I'm not sure about the special library. The "kicad special library" google search yielded https://forum.kicad.info/t/the-following-libraries-were-not-found-special-solved/870 which might be a KiCad bug. Could you please look into it some more?

Thank you so much!
