### ISSUE TITLE
Move via farther from the pad of CR6 on the left main PCB

### ISSUE THREAD

**Issue by spuder** [UltimateHackingKeyboard/electronics#8]
<img width="1174" alt="screen shot 2015-12-09 at 10 32 28 pm" src="https://cloud.githubusercontent.com/assets/242382/11707688/e6c92580-9ec4-11e5-9f8b-971762b76d9b.png">

**Comment by mondalaci** [comment]
Not relevant anymore. Individual ESD suppressors have been replaced with ESD suppressor arrays. These kinds of issues will be resolved regardless.
